apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-user-operator
  namespace: kafka
  labels:
    app: strimzi
subjects:
  - kind: ServiceAccount
    name: strimzi-user-operator
roleRef:
  kind: Role
  name: strimzi-user-operator
  apiGroup: rbac.authorization.k8s.io